//
//  Keys.swift
//  GApp2
//
//  Created by Robert Talianu
//

import Foundation

struct KeyboardKey: Identifiable {
    let id = UUID()
    let name: String
    let keyCode: UInt8
    let modifier: UInt8
}

// Example mapping (expand as needed)
let KeyboardKeysMapping: [KeyboardKey] = [
    //
    KeyboardKey(name: "Right Arrow", keyCode: 0x4F, modifier: 0x00),
    KeyboardKey(name: "Left Arrow", keyCode: 0x50, modifier: 0x00),
    KeyboardKey(name: "Down Arrow", keyCode: 0x51, modifier: 0x00),
    KeyboardKey(name: "Up Arrow", keyCode: 0x52, modifier: 0x00),
    //
    KeyboardKey(name: "Page Up", keyCode: 0x4B, modifier: 0x00),
    KeyboardKey(name: "Page Down", keyCode: 0x4E, modifier: 0x00),
    KeyboardKey(name: "Home", keyCode: 0x4A, modifier: 0x00),
    KeyboardKey(name: "End", keyCode: 0x4D, modifier: 0x00),
    KeyboardKey(name: "Insert", keyCode: 0x49, modifier: 0x00),
    KeyboardKey(name: "Delete", keyCode: 0x4C, modifier: 0x00),
    //
    KeyboardKey(name: "Enter", keyCode: 0x28, modifier: 0x00),
    KeyboardKey(name: "Space", keyCode: 0x2C, modifier: 0x00),
    KeyboardKey(name: "Escape", keyCode: 0x29, modifier: 0x00),
    //
    KeyboardKey(name: "A", keyCode: 0x04, modifier: 0x02),
    KeyboardKey(name: "B", keyCode: 0x05, modifier: 0x02),
    KeyboardKey(name: "C", keyCode: 0x06, modifier: 0x02),
    KeyboardKey(name: "D", keyCode: 0x07, modifier: 0x02),
    KeyboardKey(name: "E", keyCode: 0x08, modifier: 0x02),
    KeyboardKey(name: "F", keyCode: 0x09, modifier: 0x02),
    KeyboardKey(name: "G", keyCode: 0x0A, modifier: 0x02),
    KeyboardKey(name: "H", keyCode: 0x0B, modifier: 0x02),
    KeyboardKey(name: "I", keyCode: 0x0C, modifier: 0x02),
    KeyboardKey(name: "J", keyCode: 0x0D, modifier: 0x02),
    KeyboardKey(name: "K", keyCode: 0x0E, modifier: 0x02),
    KeyboardKey(name: "L", keyCode: 0x0F, modifier: 0x02),
    KeyboardKey(name: "M", keyCode: 0x10, modifier: 0x02),
    KeyboardKey(name: "N", keyCode: 0x11, modifier: 0x02),
    KeyboardKey(name: "O", keyCode: 0x12, modifier: 0x02),
    KeyboardKey(name: "P", keyCode: 0x13, modifier: 0x02),
    KeyboardKey(name: "Q", keyCode: 0x14, modifier: 0x02),
    KeyboardKey(name: "R", keyCode: 0x15, modifier: 0x02),
    KeyboardKey(name: "S", keyCode: 0x16, modifier: 0x02),
    KeyboardKey(name: "T", keyCode: 0x17, modifier: 0x02),
    KeyboardKey(name: "U", keyCode: 0x18, modifier: 0x02),
    KeyboardKey(name: "V", keyCode: 0x19, modifier: 0x02),
    KeyboardKey(name: "W", keyCode: 0x1A, modifier: 0x02),
    KeyboardKey(name: "X", keyCode: 0x1B, modifier: 0x02),
    KeyboardKey(name: "Y", keyCode: 0x1C, modifier: 0x02),
    KeyboardKey(name: "Z", keyCode: 0x1D, modifier: 0x02),
    //
    KeyboardKey(name: "0", keyCode: 0x27, modifier: 0x00),
    KeyboardKey(name: "1", keyCode: 0x1E, modifier: 0x00),
    KeyboardKey(name: "2", keyCode: 0x1F, modifier: 0x00),
    KeyboardKey(name: "3", keyCode: 0x20, modifier: 0x00),
    KeyboardKey(name: "4", keyCode: 0x21, modifier: 0x00),
    KeyboardKey(name: "5", keyCode: 0x22, modifier: 0x00),
    KeyboardKey(name: "6", keyCode: 0x23, modifier: 0x00),
    KeyboardKey(name: "7", keyCode: 0x24, modifier: 0x00),
    KeyboardKey(name: "8", keyCode: 0x25, modifier: 0x00),
    KeyboardKey(name: "9", keyCode: 0x26, modifier: 0x00),
    //
    KeyboardKey(name: "a", keyCode: 0x04, modifier: 0x00),
    KeyboardKey(name: "b", keyCode: 0x05, modifier: 0x00),
    KeyboardKey(name: "c", keyCode: 0x06, modifier: 0x00),
    KeyboardKey(name: "d", keyCode: 0x07, modifier: 0x00),
    KeyboardKey(name: "e", keyCode: 0x08, modifier: 0x00),
    KeyboardKey(name: "f", keyCode: 0x09, modifier: 0x00),
    KeyboardKey(name: "g", keyCode: 0x0A, modifier: 0x00),
    KeyboardKey(name: "h", keyCode: 0x0B, modifier: 0x00),
    KeyboardKey(name: "i", keyCode: 0x0C, modifier: 0x00),
    KeyboardKey(name: "j", keyCode: 0x0D, modifier: 0x00),
    KeyboardKey(name: "k", keyCode: 0x0E, modifier: 0x00),
    KeyboardKey(name: "l", keyCode: 0x0F, modifier: 0x00),
    KeyboardKey(name: "m", keyCode: 0x10, modifier: 0x00),
    KeyboardKey(name: "n", keyCode: 0x11, modifier: 0x00),
    KeyboardKey(name: "o", keyCode: 0x12, modifier: 0x00),
    KeyboardKey(name: "p",  keyCode: 0x13, modifier: 0x00),
    KeyboardKey(name: "q", keyCode: 0x14, modifier: 0x00),
    KeyboardKey(name: "r", keyCode: 0x15, modifier: 0x00),
    KeyboardKey(name: "s", keyCode: 0x16, modifier: 0x00),
    KeyboardKey(name: "t", keyCode: 0x17, modifier: 0x00),
    KeyboardKey(name: "u", keyCode: 0x18, modifier: 0x00),
    KeyboardKey(name: "v", keyCode: 0x19, modifier: 0x00),
    KeyboardKey(name: "w", keyCode: 0x1A, modifier: 0x00),
    KeyboardKey(name: "x", keyCode: 0x1B, modifier: 0x00),
    KeyboardKey(name: "y", keyCode: 0x1C, modifier: 0x00),
    KeyboardKey(name: "z", keyCode: 0x1D, modifier: 0x00),
    //
    KeyboardKey(name: "`", keyCode: 0x2D, modifier: 0x00),
    KeyboardKey(name: "-", keyCode: 0x2D, modifier: 0x02),
    KeyboardKey(name: "=", keyCode: 0x2E, modifier: 0x02),
    KeyboardKey(name: "[", keyCode: 0x2F, modifier: 0x02),
    KeyboardKey(name: "]", keyCode: 0x30, modifier: 0x02),
    KeyboardKey(name: "\\", keyCode: 0x31, modifier: 0x02),
    KeyboardKey(name: ";", keyCode: 0x33, modifier: 0x02),
    KeyboardKey(name: "'", keyCode: 0x34, modifier: 0x02),
    KeyboardKey(name: ",", keyCode: 0x36, modifier: 0x02),
    KeyboardKey(name: ".", keyCode: 0x37, modifier: 0x02),
    KeyboardKey(name: "/", keyCode: 0x38, modifier: 0x02),
    //
    KeyboardKey(name: "F1", keyCode: 0x3A, modifier: 0x00),
    KeyboardKey(name: "F2", keyCode: 0x3B, modifier: 0x00),
    KeyboardKey(name: "F3", keyCode: 0x3C, modifier: 0x00),
    KeyboardKey(name: "F4", keyCode: 0x3D, modifier: 0x00),
    KeyboardKey(name: "F5", keyCode: 0x3E, modifier: 0x00),
    KeyboardKey(name: "F6", keyCode: 0x3F, modifier: 0x00),
    KeyboardKey(name: "F7", keyCode: 0x40, modifier: 0x00),
    KeyboardKey(name: "F8", keyCode: 0x41, modifier: 0x00),
    KeyboardKey(name: "F9", keyCode: 0x42, modifier: 0x00),
    KeyboardKey(name: "F10", keyCode: 0x43, modifier: 0x00),
    KeyboardKey(name: "F11", keyCode: 0x44, modifier: 0x00),
    KeyboardKey(name: "F12", keyCode: 0x45, modifier: 0x00),
    //
    KeyboardKey(name: "Print Screen", keyCode: 0x46, modifier: 0x00),
    KeyboardKey(name: "Scroll Lock", keyCode: 0x47, modifier: 0x00),
    KeyboardKey(name: "Pause", keyCode: 0x48, modifier: 0x00),
    //
    KeyboardKey(name: "Num Lock", keyCode: 0x53, modifier: 0x00),
    KeyboardKey(name: "Num 0", keyCode: 0x62, modifier: 0x00),
    KeyboardKey(name: "Num 1", keyCode: 0x59, modifier: 0x00),
    KeyboardKey(name: "Num 2", keyCode: 0x5A, modifier: 0x00),
    KeyboardKey(name: "Num 3", keyCode: 0x5B, modifier: 0x00),
    KeyboardKey(name: "Num 4", keyCode: 0x5C, modifier: 0x00),
    KeyboardKey(name: "Num 5", keyCode: 0x5D, modifier: 0x00),
    KeyboardKey(name: "Num 6", keyCode: 0x5E, modifier: 0x00),
    KeyboardKey(name: "Num 7", keyCode: 0x5F, modifier: 0x00),
    KeyboardKey(name: "Num 8", keyCode: 0x60, modifier: 0x00),
    KeyboardKey(name: "Num 9", keyCode: 0x61, modifier: 0x00),
    KeyboardKey(name: "Num /", keyCode: 0x54, modifier: 0x00),
    KeyboardKey(name: "Num *", keyCode: 0x55, modifier: 0x00),
    KeyboardKey(name: "Num -", keyCode: 0x56, modifier: 0x00),
    KeyboardKey(name: "Num +", keyCode: 0x57, modifier: 0x00),
    KeyboardKey(name: "Num .", keyCode: 0x63, modifier: 0x00),
    KeyboardKey(name: "Num Enter", keyCode: 0x58, modifier: 0x00),
    //
    KeyboardKey(name: "Backspace", keyCode: 0x2A, modifier: 0x00),
    KeyboardKey(name: "Tab", keyCode: 0x2B, modifier: 0x00),
    KeyboardKey(name: "Caps Lock", keyCode: 0x39, modifier: 0x00),
    KeyboardKey(name: "Left Shift", keyCode: 0xE1, modifier: 0x00),
    KeyboardKey(name: "Right Shift", keyCode: 0xE5, modifier: 0x00),
    KeyboardKey(name: "Left Control", keyCode: 0xE0, modifier: 0x00),
    KeyboardKey(name: "Right Control", keyCode: 0xE4, modifier: 0x00),
    KeyboardKey(name: "Left Alt", keyCode: 0xE2, modifier: 0x00),
    KeyboardKey(name: "Right Alt", keyCode: 0xE6, modifier: 0x00),
    KeyboardKey(name: "Left GUI", keyCode: 0xE3, modifier: 0x00),
    KeyboardKey(name: "Right GUI", keyCode: 0xE7, modifier: 0x00),
    //
    KeyboardKey(name: "!", keyCode: 0x1E, modifier: 0x02),
    KeyboardKey(name: "@", keyCode: 0x1F, modifier: 0x02),
    KeyboardKey(name: "#", keyCode: 0x20, modifier: 0x02),
    KeyboardKey(name: "$", keyCode: 0x21, modifier: 0x02),
    KeyboardKey(name: "%", keyCode: 0x22, modifier: 0x02),
    KeyboardKey(name: "^", keyCode: 0x23, modifier: 0x02),
    KeyboardKey(name: "&", keyCode: 0x24, modifier: 0x02),
    KeyboardKey(name: "*", keyCode: 0x25, modifier: 0x02),
    KeyboardKey(name: "(", keyCode: 0x26, modifier: 0x02),
    KeyboardKey(name: ")", keyCode: 0x27, modifier: 0x02),
    KeyboardKey(name: "_", keyCode: 0x2D, modifier: 0x02),
    KeyboardKey(name: "+", keyCode: 0x2E, modifier: 0x02),
    KeyboardKey(name: "{", keyCode: 0x2F, modifier: 0x02),
    KeyboardKey(name: "}", keyCode: 0x30, modifier: 0x02),
    KeyboardKey(name: "|", keyCode: 0x31, modifier: 0x02),
    KeyboardKey(name: ":", keyCode: 0x33, modifier: 0x02),
    KeyboardKey(name: "\"", keyCode: 0x34, modifier: 0x02),
    KeyboardKey(name: "<", keyCode: 0x36, modifier: 0x02),
    KeyboardKey(name: ">", keyCode: 0x37, modifier: 0x02),
    KeyboardKey(name: "?", keyCode: 0x38, modifier: 0x02)
]
